version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      # Local PostgreSQL
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=movies_db
      # Server PostgreSQL (uncomment to use)
      # - DB_HOST=dpg-cv9mftjqf0us73c9jbh0-a.oregon-postgres.render.com
      # - DB_PORT=5432
      # - DB_USER=forsiy
      # - DB_PASSWORD=SyX0cDwvxnDtZdcqdsHRIVYy3H76yagJ
      # - DB_NAME=movies_db_a481
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: